version: "3.8"

services:
  produk:
    build: ./produk
    ports:
      - "8081:8080"

  pelanggan:
    build: ./pelanggan
    ports:
      - "8082:8080"

  order:
    build: ./order
    ports:
      - "8083:8080"
